# Generated by Django 5.2.14 on 2026-05-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authro',
            new_name='author',
        ),
    ]
